'use server'

/**
 * ************ By Inova Digital Marketing ***************
 * ******************* inovamkt.io ************************
 * ******************* Paulo Daian ************************
 * *************** contact@inovamkt.io ******************
 */


import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'

export async function getTeamMembersAction() {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return []

    const { data: adminProfile } = await supabase.from('users').select('tenant_id, role').eq('id', user.id).single()
    if (!adminProfile?.tenant_id) return []

    const { data } = await supabase.from('users')
        .select('*')
        .eq('tenant_id', adminProfile.tenant_id)
        .order('created_at', { ascending: true })

    return data || []
}

export async function createAgentAction(formData: any) {
    const { name, email, phone, password, roleLevel } = formData
    
    if (!name || !email || !password) {
        return { success: false, error: 'Name, email and password are required' }
    }
    
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { success: false, error: 'Unauthorized' }

    // Check if user is admin
    const { data: adminProfile } = await supabase.from('users').select('tenant_id, role').eq('id', user.id).single()
    if (adminProfile?.role !== 'admin') {
        return { success: false, error: 'Only admins can add agents' }
    }

    const tenantId = adminProfile.tenant_id

    // Check limit on agents/members for the tenant
    const { count } = await supabase.from('users')
        .select('*', { count: 'exact', head: true })
        .eq('tenant_id', tenantId)

    if (count !== null && count >= 4) { // 1 owner + 3 agents
        return { success: false, error: 'Team size limit reached (max 3 agents)' }
    }

    const supabaseAdmin = createAdminClient()

    // Create auth user natively
    const { data: newUser, error: authError } = await supabaseAdmin.auth.admin.createUser({
        email,
        password,
        phone: phone || undefined,
        email_confirm: true,
        phone_confirm: true,
        user_metadata: { name }
    })

    if (authError || !newUser?.user) {
        return { success: false, error: authError?.message || 'Failed to create user auth' }
    }

    // Force updates the public.users record which is generated by the user's Supabase auth trigger.
    const { error: updateError } = await supabaseAdmin.from('users').update({
        tenant_id: tenantId,
        role: roleLevel === 'admin' ? 'admin' : 'agent',
        full_name: name,
        phone,
        email
    }).eq('id', newUser.user.id)

    if (updateError) {
        // Fallback cleanup
        console.error('Failed to link tenant', updateError)
        await supabaseAdmin.auth.admin.deleteUser(newUser.user.id)
        return { success: false, error: 'Failed to assign user to your workspace' }
    }

    revalidatePath('/dashboard/settings/team')
    return { success: true }
}

export async function deleteAgentAction(agentId: string) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { success: false, error: 'Unauthorized' }

    if (agentId === user.id) return { success: false, error: 'Cannot delete yourself' }

    const { data: adminProfile } = await supabase.from('users').select('tenant_id, role').eq('id', user.id).single()
    if (adminProfile?.role !== 'admin') {
        return { success: false, error: 'Only admins can delete team members' }
    }

    const supabaseAdmin = createAdminClient()
    // Native auth deletion cascades to public.users via Foreign Key constraints.
    const { error } = await supabaseAdmin.auth.admin.deleteUser(agentId)

    if (error) {
        return { success: false, error: error.message }
    }

    revalidatePath('/dashboard/settings/team')
    return { success: true }
}

export async function updateAgentAction(formData: any) {
    const { id, name, email, phone, password, roleLevel } = formData
    
    if (!id || !name) {
        return { success: false, error: 'ID and Name are required' }
    }
    
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { success: false, error: 'Unauthorized' }

    // Check if user is admin
    const { data: adminProfile } = await supabase.from('users').select('tenant_id, role').eq('id', user.id).single()
    if (adminProfile?.role !== 'admin') {
        return { success: false, error: 'Only admins can update team members' }
    }

    const supabaseAdmin = createAdminClient()

    // Update auth user if password is provided
    if (password && password.trim().length > 0) {
        const { error: authError } = await supabaseAdmin.auth.admin.updateUserById(id, {
            password,
            user_metadata: { name }
        })
        if (authError) return { success: false, error: authError.message }
    }

    // Update public.users
    const { error: updateError } = await supabaseAdmin.from('users').update({
        role: roleLevel === 'admin' ? 'admin' : 'agent',
        full_name: name,
        phone,
        email: email || undefined
    }).eq('id', id).eq('tenant_id', adminProfile.tenant_id) // Safety bounds

    if (updateError) {
        return { success: false, error: 'Failed to update user profile' }
    }

    revalidatePath('/dashboard/settings/team')
    return { success: true }
}

import { sendWhatsAppMessage } from '@/lib/whatsapp-service'

export async function sendAgentCredentialsWhatsappAction(phone: string, text: string) {
    if (!phone || !text) return { success: false, error: 'Phone and text are required' }

    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { success: false, error: 'Unauthorized' }

    const { data: adminProfile } = await supabase.from('users').select('tenant_id, role').eq('id', user.id).single()
    if (!adminProfile?.tenant_id) return { success: false, error: 'Tenant not found' }

    try {
        const res = await sendWhatsAppMessage({
            phone,
            message: text,
            tenantId: adminProfile.tenant_id
        })
        
        if (!res?.success) {
            return { success: false, error: res?.error || 'Failed to send WhatsApp message via Evolution API' }
        }

        return { success: true }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}
